---
milestones:
  - 'R2 (v3.0.0)'
  - 'R3 (v4.0.0)'
  - 'R4 (v5.0.0)'
  - 'R5 (v6.0.0)'

labels:
  - name: bug
    description: "Something isn't working"
    color: "d73a4a"
  - name: documentation
    description: "Improvements or additions to documentation"
    color: "0075ca"
  - name: duplicate
    description: "This issue or pull request already exists"
    color: "cfd3d7"
  - name: enhancement
    description: "New feature or request"
    color: "a2eeef"
  - name: good first issue
    description: "Good for newcomers"
    color: "7057ff"
  - name: help wanted
    description: "Extra attention is needed"
    color: "008672"
  - name: invalid
    description: "This doesn't seem right"
    color: "e4e669"
  - name: question
    description: "Further information is requested"
    color: "d876e3"
  - name: support
    description: "Support request"
    color: "e99695"
  - name: wontfix
    description: "This will not be worked on"
    color: "ffffff"
  - name: on hold
    description: "Is on hold"
    color: "000000"
  - name: upstream
    description: "Implemented directly in the upstream"
    color: "0052cc"
  - name: housekeeping
    description: "Internal housekeeping"
    color: "d93f0b"
  - name: dependencies
    description: "Pull requests that update a dependency file"
    color: "0366d6"
  - name: security
    description: "Issues or pull requests that are security-relevant"
    color: "fc0000"
  - name: work in progress
    description: "Pull requests that are work in progress, do not merge them"
    color: "c5def5"
  - name: needs refinement
    description: "User stories that need to be refined for further progress"
    color: "8cb1fe"
  - name: IaaS
    description: "Issues or pull requests relevant for Team1: IaaS"
    color: "3d51e5"
  - name: Container
    description: "Issues or pull requests relevant for Team 2: Container Infra and Tooling"
    color: "0dce67"
  - name: Ops
    description: "Issues or pull requests relevant for Team 3: Ops Tooling"
    color: "f3de42"
  - name: Community
    description: "Issues or pull requests relevant for SIG Community"
    color: "26a69a"
  - name: IAM
    description: "Issues or pull requests relevant for SIG IAM"
    color: "7cb342"
  - name: osism
    description: "Issues or pull requests relevant for osism"
    color: "f4511e"
  - name: epic
    description: "Issues that are spread across multiple sprints"
    color: "6a5acd"
  - name: release3
    description: "Issues or pull requests that are aimed for release 3"
    color: "51e898"
  - name: action required
    description: "Issues or pull requests that urgently require action"
    color: "dc143c"
  - name: regression
    description: "Issues or pull requests that address a regression"
    color: "ffd700"
  - name: longterm
    description: "Issues or pull requests that relevent for longterm support"
    color: "ff00ff"
  - name: standards
    description: "Issues / ADR / pull requests relevant for standardization & certification"
    color: "50c3a5"
